exit = True
table = {
    'A' : '80',
    'B' : '81',
    'C' : '82',
    'D' : '83',
    'E' : '84',
    'F' : '85',
    'G' : '86',
    'H' : '87',
    'I' : '88',
    'J' : '89',
    'K' : '8A',
    'L' : '8B',
    'M' : '8C',
    'N' : '8D',
    'O' : '8E',
    'P' : '8F',
    'Q' : '90',
    'R' : '91',
    'S' : '92',
    'T' : '93',
    'U' : '94',
    'V' : '95',
    'W' : '96',
    'X' : '97',
    'Y' : '98',
    'Z' : '99',
    '(' : '9A',
    ')' : '9B',
    ':' : '9C',
    ';' : '9D',
    '[' : '9E',
    ']' : '9F',
    'a' : 'A0',
    'b' : 'A1',
    'c' : 'A2',
    'd' : 'A3',
    'e' : 'A4',
    'f' : 'A5',
    'g' : 'A6',
    'h' : 'A7',
    'i' : 'A8',
    'j' : 'A9',
    'k' : 'AA',
    'l' : 'AB',
    'm' : 'AC',
    'n' : 'AD',
    'o' : 'AE',
    'p' : 'AF',
    'q' : 'B0',
    'r' : 'B1',
    's' : 'B2',
    't' : 'B3',
    'u' : 'B4',
    'v' : 'B5',
    'w' : 'B6',
    'x' : 'B7',
    'y' : 'B8',
    'z' : 'B9',
    ' ' : '7F',
}

while(exit):
    texto = input("Insira o texto: ")
    resposta = ""
    for i in range(len(texto)):
        resposta = resposta+table[texto[i]]+" "
    print(resposta)
